spring.application.name=backend
frontend.url=${FRONTEND_URL}

# Database configuration (TiDB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode = always
spring.docker.compose.enabled=false

# JWT configuration
jwt.expiration = 3600000
jwt.secret = ${JWT_SECRET}

# Minio configuration (Backblaze B2)
minio.url=https://s3.eu-central-003.backblazeb2.com
minio.access.key=${MINIO_ACCESS_KEY}
minio.secret.key=${MINIO_SECRET_KEY}
minio.bucket.name=expense-tracker-receipts
minio.region=eu-central-003

# RabbitMQ configuration (CloudAMQP)
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=pgxfddnd
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.virtual-host=pgxfddnd

# Sender configuration
rabbitmq.queue.name=expense.queue
rabbitmq.exchange.name=expense.exchange
rabbitmq.routing.key=expense.routing.key

# Receiver configuration
rabbitmq.result.queue.name=expense.result.queue
rabbitmq.result.routing.key=expense.result.routing.key
